on: [push]

permissions:
  contents: read
  pull-requests: write
  actions: write
  statuses: write
  pages: write
  deployments: write
  checks: write
  discussions: write
  id-token: write
  issues: write
  packages: write
  repository-projects: read
  security-events: read

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v1
      - run: npm test

      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
